### ISSUE TITLE
"Max retries exceeded with url" error [Anki Version ⁨2.1.54 (b6a7760c)⁩ Python 3.9.7 Qt 6.3.1 PyQt 6.3.1]

### ISSUE THREAD

**Issue by sccriabin** [Language-Tools/anki-language-tools#87]
I own a paid subscription. I encountered this error in the browser. Was trying to generate a simple cambridge brit pronunciation for a word.

The following problem was encountered:
HTTPSConnectionPool(host='dictionary.cambridge.org', port=443): Max retries exceeded with url: /de/worterbuch/englisch/arrive (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x145014130>, 'Connection to dictionary.cambridge.org timed out. (connect timeout=15)')) (1 time)

**Comment by luc-languagetools** [comment]
Hi @sccriabin, I assume you're talking about HyperTTS ? The paid subscription guarantees access to premium services such as Azure, Google, Amazon. Cambridge is a free service and it's a dictionary service , so its reliability is not guarantee.
