### ISSUE TITLE
On editor, "Speak", "Choose Translation" and "Play" functions do not appear 

### ISSUE THREAD

**Issue by willetcardenas** [Language-Tools/anki-language-tools#89]
Hi there, 
Recently downloaded the language tools add-on and have been enjoying the ease of use so far. However, I've found that the "Choose Translation" function does not appear on editor, among others. Also, when I add new notes it does not seem to generate translation/transliterations/etc automatically.

<img width="669" alt="Screenshot 2022-08-20 194759" src="https://user-images.githubusercontent.com/111657743/185762073-65184fd9-103b-428a-a929-d96184a41985.png">

**Comment by luc-languagetools** [comment]
Hi, on Anki 2.1.50, those features are now accessible from a right-click, you can see a screenshot here: https://languagetools.anki.study/updates#2022-04-12

**Comment by willetcardenas** [comment]
Great, amazing. Thanks very much:)
